// NOUARA is an invented handbag brand, built by Broda Dev as a demonstration
// of an Algerian cash-on-delivery product page. Prices are example prices.

export const COLORS = [
  { id: "camel", swatch: "#9a5a2e" },
  { id: "noir", swatch: "#1d1b1a" },
  { id: "bordeaux", swatch: "#5c1a24" },
] as const;

export type ColorId = (typeof COLORS)[number]["id"];

export const PRICE = 6900;
export const OLD_PRICE = 8500;
/** Width × height × depth, in cm; kept apart from the words so it reads left to right in Arabic. */
export const DIMS = "24 × 18 × 10";

const fr = {
  banner: "Démo réalisée par Broda Dev · NOUARA est une marque inventée, aucune commande n'est envoyée.",
  bannerBack: "Retour à Broda Dev",
  announce: "Livraison dans les 58 wilayas · Paiement à la livraison · Échange sous 7 jours",
  nav: ["Nouveautés", "Sacs à main", "Bandoulières", "Pochettes"],
  search: "Rechercher",
  bag: "Panier",
  crumbs: ["Accueil", "Sacs à main"],
  kicker: "Collection Tlemcen",
  title: "Sac Nouara à fermoir fleur",
  save: "-19 %",
  currency: "DA",
  colorLabel: "Couleur",
  colors: { camel: "Camel", noir: "Noir", bordeaux: "Bordeaux" } as Record<ColorId, string>,
  dimsLabel: "Dimensions",
  dimsUnit: "cm",
  dimsNote: "Anse et bandoulière amovible",
  qtyLabel: "Quantité",
  less: "Moins",
  more: "Plus",
  stock: "Plus que 4 pièces dans ce coloris",
  formTitle: "Commander",
  formSub: "Paiement à la livraison",
  name: "Nom et prénom",
  namePh: "Ex : Amina Belkacem",
  phone: "Téléphone",
  phonePh: "05 XX XX XX XX",
  wilaya: "Wilaya",
  wilayaPh: "Choisir la wilaya",
  commune: "Commune",
  communePh: "Votre commune",
  delivery: "Livraison",
  deskTitle: "Bureau (Stop desk)",
  deskSub: "Retrait au point relais",
  homeTitle: "À domicile",
  homeSub: "Livré à votre porte",
  pickWilaya: "Choisissez la wilaya",
  sumPrice: "Prix",
  sumDelivery: "Livraison",
  sumTotal: "Total",
  order: "Commander",
  payNote: "Vous payez à la réception. Aucun paiement en ligne.",
  required: "Champ obligatoire",
  phoneInvalid: "Numéro à 10 chiffres, commençant par 05, 06 ou 07",
  doneTitle: "Merci, votre commande est enregistrée !",
  doneBody: "Ceci est une démo : aucune commande n'a été envoyée. Sur un vrai site, la boutique vous appellerait pour confirmer.",
  doneAgain: "Refaire une commande",
  trust: ["Livraison en 24 à 72 h", "Échange sous 7 jours", "Paiement à la livraison"],
  descTitle: "Le sac",
  desc: "Un sac à main structuré aux coins arrondis, en cuir lisse, fermé par une fleur en laiton doré à cinq pétales : l'emblème de NOUARA. Il se porte à la main ou à l'épaule.",
  details: ["Cuir lisse, doublure en toile", "Fermoir fleur en laiton doré", "Anse et bandoulière réglable, amovible", "Une poche zippée et une poche plaquée à l'intérieur"],
  alt: {
    camel: "Sac NOUARA camel, vue de face",
    noir: "Sac NOUARA noir, vue de face",
    bordeaux: "Sac NOUARA bordeaux, vue de face",
    portee: "Le sac NOUARA camel porté à la main dans une ruelle de Tlemcen",
    detail: "Le fermoir fleur en laiton doré, de près",
    interieur: "L'intérieur du sac : doublure en toile, poche zippée et poche plaquée",
    trio: "Les trois coloris côte à côte : noir, camel et bordeaux",
  },
};

const ar: typeof fr = {
  banner: "مثال من إنجاز Broda Dev · NOUARA علامة وهمية، ولا تُرسَل أي طلبية.",
  bannerBack: "العودة إلى Broda Dev",
  announce: "التوصيل إلى 58 ولاية · الدفع عند الاستلام · استبدال خلال 7 أيام",
  nav: ["الجديد", "حقائب اليد", "حقائب الكتف", "محافظ صغيرة"],
  search: "بحث",
  bag: "السلة",
  crumbs: ["الرئيسية", "حقائب اليد"],
  kicker: "تشكيلة تلمسان",
  title: "حقيبة نوّارة بقفل الوردة",
  save: "-19%",
  currency: "دج",
  colorLabel: "اللون",
  colors: { camel: "كاميل", noir: "أسود", bordeaux: "عنّابي" },
  dimsLabel: "المقاسات",
  dimsUnit: "سم",
  dimsNote: "مقبض وحزام كتف قابل للنزع",
  qtyLabel: "الكمية",
  less: "أقل",
  more: "أكثر",
  stock: "بقيت 4 قطع فقط من هذا اللون",
  formTitle: "اطلبي الآن",
  formSub: "الدفع عند الاستلام",
  name: "الاسم واللقب",
  namePh: "مثال: أمينة بلقاسم",
  phone: "رقم الهاتف",
  phonePh: "05 XX XX XX XX",
  wilaya: "الولاية",
  wilayaPh: "اختاري الولاية",
  commune: "البلدية",
  communePh: "بلديتك",
  delivery: "التوصيل",
  deskTitle: "إلى المكتب · Stop desk",
  deskSub: "الاستلام من نقطة التوصيل",
  homeTitle: "إلى المنزل",
  homeSub: "يصلك إلى باب بيتك",
  pickWilaya: "اختاري الولاية",
  sumPrice: "السعر",
  sumDelivery: "التوصيل",
  sumTotal: "المجموع",
  order: "اطلبي الآن",
  payNote: "تدفعين عند الاستلام. لا دفع عبر الإنترنت.",
  required: "حقل إجباري",
  phoneInvalid: "رقم من 10 أرقام يبدأ بـ 05 أو 06 أو 07",
  doneTitle: "شكراً، تم تسجيل طلبيتك!",
  doneBody: "هذا مثال فقط: لم تُرسَل أي طلبية. في متجر حقيقي، يتصل بك المتجر لتأكيد الطلب.",
  doneAgain: "طلبية جديدة",
  trust: ["توصيل خلال 24 إلى 72 ساعة", "استبدال خلال 7 أيام", "الدفع عند الاستلام"],
  descTitle: "الحقيبة",
  desc: "حقيبة يد متماسكة بزوايا مستديرة، من الجلد الأملس، تُغلق بوردة من النحاس المذهّب بخمس بتلات: شعار NOUARA. تُحمل باليد أو على الكتف.",
  details: ["جلد أملس وبطانة من القماش", "قفل وردة من النحاس المذهّب", "مقبض وحزام كتف قابل للتعديل والنزع", "جيب داخلي بسحّاب وجيب مفتوح"],
  alt: {
    camel: "حقيبة NOUARA بلون الكاميل، من الأمام",
    noir: "حقيبة NOUARA باللون الأسود، من الأمام",
    bordeaux: "حقيبة NOUARA باللون العنّابي، من الأمام",
    portee: "حقيبة NOUARA بلون الكاميل محمولة باليد في زقاق من تلمسان",
    detail: "قفل الوردة من النحاس المذهّب عن قرب",
    interieur: "داخل الحقيبة: بطانة من القماش، جيب بسحّاب وجيب مفتوح",
    trio: "الألوان الثلاثة جنباً إلى جنب: أسود، كاميل وعنّابي",
  },
};

export const COPY = { fr, ar };
