// ZNIQA is an invented streetwear brand, built by Broda Dev as a demonstration
// of an Algerian cash-on-delivery product page. Prices are example prices.

export const COLORS = [
  { id: "noir", swatch: "#2b2b2a" },
  { id: "blanc", swatch: "#ece9e2" },
  { id: "sable", swatch: "#cdb99a" },
  { id: "olive", swatch: "#7d8466" },
] as const;

export type ColorId = (typeof COLORS)[number]["id"];

export const SIZES = ["S", "M", "L", "XL", "XXL"] as const;

export const PRICE = 2500;
export const OLD_PRICE = 3200;

const fr = {
  banner: "Démo réalisée par Broda Dev · ZNIQA est une marque inventée, aucune commande n'est envoyée.",
  bannerBack: "Retour à Broda Dev",
  announce: "Livraison dans les 58 wilayas · Paiement à la livraison",
  nav: ["Nouveautés", "T-shirts", "Hoodies", "Pantalons"],
  search: "Rechercher",
  bag: "Panier",
  crumbs: ["Accueil", "T-shirts"],
  kicker: "Nouvelle collection",
  title: "T-shirt oversize Étoile",
  save: "-22 %",
  currency: "DA",
  colorLabel: "Couleur",
  colors: { noir: "Noir délavé", blanc: "Blanc cassé", sable: "Sable", olive: "Olive" } as Record<ColorId, string>,
  sizeLabel: "Taille",
  sizeGuide: "Guide des tailles",
  qtyLabel: "Quantité",
  less: "Moins",
  more: "Plus",
  stock: "Plus que 7 pièces dans cette taille",
  formTitle: "Commander",
  formSub: "Paiement à la livraison",
  name: "Nom et prénom",
  namePh: "Ex : Yacine Belkacem",
  phone: "Téléphone",
  phonePh: "05 XX XX XX XX",
  wilaya: "Wilaya",
  wilayaPh: "Choisir la wilaya",
  commune: "Commune",
  communePh: "Votre commune",
  delivery: "Livraison",
  deskTitle: "Bureau (Stop desk)",
  deskSub: "Retrait au point relais",
  homeTitle: "À domicile",
  homeSub: "Livré à votre porte",
  pickWilaya: "Choisissez la wilaya",
  sumPrice: "Prix",
  sumDelivery: "Livraison",
  sumTotal: "Total",
  order: "Commander",
  payNote: "Vous payez à la réception. Aucun paiement en ligne.",
  required: "Champ obligatoire",
  phoneInvalid: "Numéro à 10 chiffres, commençant par 05, 06 ou 07",
  doneTitle: "Merci, votre commande est enregistrée !",
  doneBody: "Ceci est une démo : aucune commande n'a été envoyée. Sur un vrai site, le vendeur vous appellerait pour confirmer.",
  doneAgain: "Refaire une commande",
  trust: ["Livraison en 24 à 72 h", "Échange sous 7 jours", "Paiement à la livraison"],
  descTitle: "Le produit",
  desc: "Coupe oversize, épaules tombantes, col côtelé épais. Coton lourd 240 g/m², étoile à huit branches brodée ton sur ton.",
  details: ["100 % coton, 240 g/m²", "Coupe oversize unisexe", "Broderie ton sur ton", "Lavage à 30 °C"],
  alt: {
    noir: "T-shirt ZNIQA noir délavé, posé à plat",
    blanc: "T-shirt ZNIQA blanc cassé, posé à plat",
    sable: "T-shirt ZNIQA sable, posé à plat",
    olive: "T-shirt ZNIQA olive, posé à plat",
    porte: "Jeune homme portant le T-shirt ZNIQA noir dans une ruelle",
    detail: "Détail de l'étoile brodée sur le coton noir",
    pile: "Les quatre coloris pliés en pile",
  },
};

const ar: typeof fr = {
  banner: "مثال من إنجاز Broda Dev · ZNIQA علامة وهمية، ولا تُرسَل أي طلبية.",
  bannerBack: "العودة إلى Broda Dev",
  announce: "التوصيل إلى 58 ولاية · الدفع عند الاستلام",
  nav: ["الجديد", "تيشيرتات", "هوديز", "سراويل"],
  search: "بحث",
  bag: "السلة",
  crumbs: ["الرئيسية", "تيشيرتات"],
  kicker: "تشكيلة جديدة",
  title: "تيشيرت أوفرسايز النجمة",
  save: "-22%",
  currency: "دج",
  colorLabel: "اللون",
  colors: { noir: "أسود باهت", blanc: "أبيض كريمي", sable: "رملي", olive: "زيتوني" },
  sizeLabel: "المقاس",
  sizeGuide: "دليل المقاسات",
  qtyLabel: "الكمية",
  less: "أقل",
  more: "أكثر",
  stock: "بقيت 7 قطع فقط في هذا المقاس",
  formTitle: "اطلب الآن",
  formSub: "الدفع عند الاستلام",
  name: "الاسم واللقب",
  namePh: "مثال: ياسين بلقاسم",
  phone: "رقم الهاتف",
  phonePh: "05 XX XX XX XX",
  wilaya: "الولاية",
  wilayaPh: "اختر الولاية",
  commune: "البلدية",
  communePh: "بلديتك",
  delivery: "التوصيل",
  deskTitle: "إلى المكتب · Stop desk",
  deskSub: "الاستلام من نقطة التوصيل",
  homeTitle: "إلى المنزل",
  homeSub: "يصلك إلى باب بيتك",
  pickWilaya: "اختر الولاية",
  sumPrice: "السعر",
  sumDelivery: "التوصيل",
  sumTotal: "المجموع",
  order: "اطلب الآن",
  payNote: "تدفع عند الاستلام. لا دفع عبر الإنترنت.",
  required: "حقل إجباري",
  phoneInvalid: "رقم من 10 أرقام يبدأ بـ 05 أو 06 أو 07",
  doneTitle: "شكراً، تم تسجيل طلبيتك!",
  doneBody: "هذا مثال فقط: لم تُرسَل أي طلبية. في متجر حقيقي، يتصل بك البائع لتأكيد الطلب.",
  doneAgain: "طلبية جديدة",
  trust: ["توصيل خلال 24 إلى 72 ساعة", "استبدال خلال 7 أيام", "الدفع عند الاستلام"],
  descTitle: "المنتج",
  desc: "قصّة أوفرسايز، أكتاف منسدلة، ياقة مضلّعة سميكة. قطن ثقيل 240 غ/م²، ونجمة ثمانية مطرّزة بنفس اللون.",
  details: ["قطن 100%، 240 غ/م²", "قصّة أوفرسايز للجنسين", "تطريز بنفس اللون", "غسيل على 30 درجة"],
  alt: {
    noir: "تيشيرت ZNIQA أسود باهت",
    blanc: "تيشيرت ZNIQA أبيض كريمي",
    sable: "تيشيرت ZNIQA رملي",
    olive: "تيشيرت ZNIQA زيتوني",
    porte: "شاب يرتدي تيشيرت ZNIQA الأسود في زقاق",
    detail: "تفصيل النجمة المطرّزة على القطن الأسود",
    pile: "الألوان الأربعة مطويّة فوق بعضها",
  },
};

export const COPY = { fr, ar };
export type ZniqaCopy = typeof fr;
