// Site copy. French is the reference: ar is typed against it, so a missing
// key is a type error. Claims follow PRODUCT.md: nothing here is invented
// (no clients beyond Lamssat Tlemcen, no figures, no prices for our work).

const fr = {
  nav: {
    home: "Broda Dev, accueil",
    main: "Navigation principale",
    services: "Services",
    software: "Logiciels",
    work: "Réalisations",
    contact: "Contact",
    quote: "Demander un devis",
    quoteShort: "Devis gratuit",
    switchLang: "Lire en arabe",
    switchShort: "ع",
    menu: "Menu",
    close: "Fermer le menu",
    skip: "Aller au contenu",
  },
  hero: {
    poster: ["De la", "caisse", "à la pub", "TikTok."],
    title: "De la caisse à la pub TikTok.",
    lead: "Logiciels de gestion, caisses, sites web, boutiques Shopify, publicité et logos : tout ce qui fait tourner votre commerce, et tout ce qui le fait vendre. Depuis Tlemcen, pour toute l'Algérie.",
    primary: "Demander un devis gratuit",
    whatsapp: "WhatsApp",
    caption: "SuperPOS, notre logiciel de caisse · Publicité d'exemple pour ZNIQA, une marque inventée",
    posAlt: "Écran de caisse SuperPOS avec un ticket en cours et la grille des produits",
    adAlt: "Publicité vidéo sponsorisée pour la marque d'exemple ZNIQA, avec le bouton Commander",
  },
  overview: {
    title: "Six métiers. Un seul partenaire.",
    lead: "Le logiciel qui fait tourner le magasin et tout ce qui amène les clients : on s'en occupe de A à Z, et vous parlez toujours à la même personne.",
    go: "Voir",
  },
  // The six services, in the order of the page. `id` is the section anchor.
  services: [
    { id: "logiciels", title: "Logiciels", long: "Logiciels de gestion", sub: "SuperPOS · G-Stock · Budget Employé", line: "Caisse, stock et paie, installés sur vos PC. Ils marchent même sans internet." },
    { id: "caisses", title: "Caisses POS", long: "Caisses POS", sub: "Supérettes, restaurants, cafés", line: "Un système de caisse pensé pour votre commerce : supérette, supermarché, restaurant ou café." },
    { id: "sites", title: "Sites web", long: "Sites web", sub: "Vitrine, entreprise, landing page", line: "Sites vitrines, sites d'entreprise et landing pages qui chargent vite sur téléphone." },
    { id: "shopify", title: "Shopify", long: "Shopify & pages produit", sub: "Boutiques et pages produit", line: "Votre boutique ouverte et configurée, avec des pages produit qui prennent les commandes." },
    { id: "publicite", title: "Publicité", long: "Publicité sponsorisée", sub: "Facebook, Instagram, TikTok", line: "Des campagnes sur Facebook, Instagram et TikTok, avec des visuels faits pour arrêter le pouce." },
    { id: "logos", title: "Logos", long: "Logos & identité", sub: "Identité de marque", line: "Un logo et une identité qui se reconnaissent de loin, sur l'enseigne comme sur le téléphone." },
  ],
  servicesLabel: "Nos six services",
  software: {
    title: "Logiciels de gestion.",
    lead: "Trois logiciels écrits ici, pour les commerces d'ici. Installés sur vos PC, vos données restent chez vous.",
    tabsLabel: "Choisir un logiciel",
    products: [
      {
        id: "superpos",
        name: "SuperPOS",
        what: "La caisse des supérettes et des commerces.",
        features: [
          "Interface en français et en arabe",
          "Fonctionne sans internet",
          "Rapide, même sur un vieux PC",
          "Carnet de dettes intégré",
          "Formation comprise",
        ],
        proof: "Écran réel de SuperPOS, recréé en HD · données d'exemple.",
        cta: "Demander une démo de SuperPOS",
        wa: "Bonjour Broda Dev, je voudrais une démo de SuperPOS.",
        alt: "Carnet de dettes de SuperPOS : liste des clients avec leur solde, et le détail des dettes et versements d'un client",
      },
      {
        id: "gstock",
        name: "G-Stock",
        what: "Le stock et la gestion du restaurant.",
        features: [
          "Achats et factures fournisseurs",
          "Sorties vers la cuisine",
          "État du stock et alertes de rupture",
          "Planning du personnel",
          "Statistiques et bilan",
        ],
        proof: "En service au restaurant Lamssat, à Tlemcen. Écran réel, chiffres d'exemple.",
        cta: "Demander une démo de G-Stock",
        wa: "Bonjour Broda Dev, je voudrais une démo de G-Stock.",
        alt: "Tableau de bord de G-Stock au restaurant Lamssat Tlemcen : achats, sorties, état du stock et produits à commander",
      },
      {
        id: "budget",
        name: "Budget Employé",
        what: "Le personnel, les présences et la paie.",
        features: [
          "Présences au jour le jour",
          "Paie au jour, à la semaine ou au mois",
          "Avances déduites automatiquement",
          "Dépenses et rapports",
        ],
        proof: "Écran de démonstration de Budget Employé.",
        cta: "Demander une démo de Budget Employé",
        wa: "Bonjour Broda Dev, je voudrais une démo de Budget Employé.",
        alt: "Tableau de bord de Budget Employé : employés actifs, présents, masse salariale, paie du mois et avances",
      },
    ],
  },
  sites: {
    title: "Sites web.",
    lead: "Un site vitrine qui donne envie de venir, une landing page qui donne envie de commander.",
    body: "Site vitrine pour votre commerce, site d'entreprise, ou landing page pour vendre un produit : rapide sur téléphone, en français et en arabe, avec le bouton WhatsApp et le formulaire de commande que vos clients connaissent.",
    features: ["Site vitrine ou site d'entreprise", "Landing page pour un produit ou une offre", "Rapide sur téléphone, en français et en arabe", "WhatsApp et formulaire de commande intégrés"],
    cta: "Essayer la landing page",
    label: "Exemples · HANOUT 13 et ZNIQA sont des marques inventées pour la démonstration.",
    siteAlt: "Site vitrine d'exemple de la supérette HANOUT 13 : promos, livraison et commande sur WhatsApp",
    landingAlt: "Landing page d'exemple du t-shirt ZNIQA sur téléphone, avec le bouton Commander toujours visible",
  },
  shopify: {
    title: "Shopify & pages produit.",
    lead: "Une page produit qui prend les commandes pour vous.",
    body: "Photos soignées, prix en DA, taille et couleur, et le formulaire que vos clients connaissent déjà : wilaya, commune, stop desk ou domicile. Ils commandent depuis leur téléphone, vous recevez la commande.",
    features: ["Nom et téléphone", "58 wilayas et commune", "Stop desk ou domicile", "Total calculé en direct", "Un bouton, une commande"],
    cta: "Essayer la démo",
    label: "Exemple · ZNIQA est une marque inventée pour la démonstration.",
    laptopAlt: "Page produit ZNIQA sur ordinateur : galerie photo, prix en DA et formulaire de commande",
    phoneAlt: "Formulaire de commande ZNIQA sur téléphone : nom, téléphone, wilaya, commune, livraison et total",
  },
  publicite: {
    title: "Publicité sponsorisée.",
    lead: "Une campagne, trois plateformes, et vous voyez ce qu'elle rapporte.",
    body: "On prépare les visuels et les vidéos, on cible les bonnes wilayas et les bons profils sur Facebook, Instagram et TikTok, puis on suit chaque commande et ce qu'elle a coûté.",
    features: ["Visuels et vidéos faits pour chaque plateforme", "Ciblage par wilaya, âge et centres d'intérêt", "Suivi des commandes et du coût par commande", "Un rapport clair, en dinars"],
    cta: "Lancer ma campagne",
    wa: "Bonjour Broda Dev, je voudrais lancer une campagne sponsorisée.",
    label: "Exemple · publicités et chiffres inventés pour la démonstration, pour la marque inventée ZNIQA.",
    dashAlt: "Tableau de bord publicitaire d'exemple : dépenses, commandes par jour, commandes par plateforme et campagnes",
    fbAlt: "Publication sponsorisée d'exemple pour ZNIQA dans un fil d'actualité, avec le bouton Commander",
    igAlt: "Photo sponsorisée d'exemple pour ZNIQA, avec la bande Commander maintenant",
    ttAlt: "Vidéo sponsorisée d'exemple pour ZNIQA, avec le bouton Commander",
  },
  logos: {
    title: "Logos & identité.",
    lead: "Un logo qui se reconnaît de loin, et tout ce qui va avec.",
    body: "On part de votre métier et de vos clients, on dessine le logo, puis on le décline : couleurs, cartes de visite, enseigne, emballages, réseaux sociaux. Vous recevez des fichiers prêts pour l'imprimeur et pour le téléphone.",
    brands: [
      { id: "lemma", name: "LEMMA", sector: "Café de quartier" },
      { id: "nouara", name: "NOUARA", sector: "Sacs et maroquinerie" },
      { id: "hanout", name: "HANOUT 13", sector: "Supérette" },
      { id: "zniqa", name: "ZNIQA", sector: "Streetwear" },
    ],
    card: { tagline: "Café de quartier", hours: "Ouvert de 6 h à 22 h", handle: "@lemma.cafe", role: "Salim · gérant" },
    teeAlt: "Le logo ZNIQA brodé sur le t-shirt",
    phoneAlt: "Profil social de HANOUT 13 : le logo en avatar et des publications aux couleurs de la marque",
    cardsAlt: "Cartes de visite du café LEMMA, recto et verso",
    cta: "Demander mon logo",
    wa: "Bonjour Broda Dev, je voudrais un logo pour mon commerce.",
    label: "Exemples · LEMMA, NOUARA, HANOUT 13 et ZNIQA sont des marques inventées pour la démonstration.",
  },
  why: {
    title: "Pourquoi Broda Dev.",
    reasons: [
      { title: "Un seul interlocuteur.", line: "Du premier message à la mise en ligne, vous parlez à la même personne. Pas de standard, pas de sous-traitant qu'on ne voit jamais." },
      { title: "D'ici, pour ici.", line: "Basé à Tlemcen. Le français et l'arabe, les dinars, les 58 wilayas, le paiement à la livraison : c'est notre point de départ, pas une option." },
      { title: "Des logiciels qui tournent vraiment.", line: "G-Stock gère le stock du restaurant Lamssat, à Tlemcen. Nos logiciels s'installent sur vos PC et marchent même sans internet." },
      { title: "Le magasin et la vente, ensemble.", line: "La caisse qui encaisse et la pub qui fait venir les clients sont faites par la même équipe, alors tout parle la même langue." },
    ],
    founder: "Omar Benassid",
    role: "Fondateur de Broda Dev · Kiffan, Tlemcen",
    write: "Écrire à Omar sur WhatsApp",
  },
  process: {
    title: "Comment ça se passe.",
    lead: "Quatre étapes, et vous savez toujours où en est votre projet.",
    steps: [
      { title: "On en parle", line: "Vous écrivez sur WhatsApp : votre commerce, ce que vous voulez vendre ou gérer." },
      { title: "Devis gratuit", line: "Vous recevez une proposition claire, sans engagement." },
      { title: "On construit", line: "Logiciel, site, boutique, campagne ou logo : on vous montre l'avancement à chaque étape." },
      { title: "Lancement", line: "Installation ou mise en ligne. Pour les logiciels, la formation est comprise." },
    ],
  },
  contact: {
    title: "Un projet ? Parlons‑en.",
    lead: "Dites-nous en deux lignes ce que vous voulez faire. Le devis est gratuit et la réponse arrive sur WhatsApp.",
    phoneLabel: "Téléphone",
    emailLabel: "E-mail",
    addressLabel: "Adresse",
    address: "Kiffan, Tlemcen",
    form: {
      name: "Votre nom",
      namePh: "Ex : Karim",
      business: "Votre commerce",
      businessPh: "Ex : supérette à Mansourah",
      service: "Ce qu'il vous faut",
      servicePh: "Choisir un service",
      message: "Votre message",
      messagePh: "Quelques mots sur votre projet",
      send: "Envoyer sur WhatsApp",
      note: "Le bouton ouvre WhatsApp avec votre message déjà écrit. Rien n'est envoyé ailleurs.",
      required: "Écrivez au moins votre nom et votre message.",
      intro: "Bonjour Broda Dev,",
      labels: { name: "Nom", business: "Commerce", service: "Service" },
    },
  },
  footer: {
    services: "Services",
    pages: "Pages",
    contact: "Contact",
    home: "Accueil",
    rights: "Broda Dev · Tlemcen, Algérie",
    examples: "Les marques ZNIQA et les autres démos sont inventées pour l'exemple.",
  },
  whatsappLabel: "Écrire à Broda Dev sur WhatsApp",
  waMessage: "Bonjour Broda Dev, je voudrais un devis gratuit.",
};

const ar: typeof fr = {
  nav: {
    home: "Broda Dev، الصفحة الرئيسية",
    main: "القائمة الرئيسية",
    services: "الخدمات",
    software: "البرامج",
    work: "أعمالنا",
    contact: "اتصل بنا",
    quote: "اطلب عرض سعر",
    quoteShort: "عرض سعر",
    switchLang: "Lire en français",
    switchShort: "FR",
    menu: "القائمة",
    close: "إغلاق القائمة",
    skip: "الانتقال إلى المحتوى",
  },
  hero: {
    poster: ["من صندوق", "الدفع", "إلى إعلان", "تيك توك."],
    title: "من صندوق الدفع إلى إعلان تيك توك.",
    lead: "برامج التسيير، أنظمة الدفع، مواقع الويب، متاجر Shopify، الإعلانات والشعارات: كل ما يُشغّل تجارتك، وكل ما يزيد مبيعاتها. من تلمسان إلى كل ولايات الجزائر.",
    primary: "اطلب عرض سعر مجاني",
    whatsapp: "واتساب",
    caption: "SuperPOS، برنامج الصندوق الخاص بنا · إعلان للعرض لعلامة مُتخيَّلة اسمها ZNIQA",
    posAlt: "شاشة الصندوق في SuperPOS مع تذكرة جارية وقائمة المنتجات",
    adAlt: "إعلان فيديو مُموَّل لعلامة المثال ZNIQA مع زر الطلب",
  },
  overview: {
    title: "ست خدمات. شريك واحد.",
    lead: "البرنامج الذي يُشغّل محلّك وكل ما يجلب لك الزبائن: نتكفّل بكل شيء من البداية إلى النهاية، وتتعامل دائماً مع نفس الشخص.",
    go: "شاهد",
  },
  services: [
    { id: "logiciels", title: "البرامج", long: "برامج التسيير", sub: "SuperPOS · G-Stock · Budget Employé", line: "الصندوق، المخزون والأجور، مثبّتة على حواسيبك. تعمل حتى بدون إنترنت." },
    { id: "caisses", title: "أنظمة الدفع", long: "أنظمة الدفع POS", sub: "متاجر، مطاعم، مقاهي", line: "نظام صندوق مناسب لتجارتك: متجر صغير، سوبرماركت، مطعم أو مقهى." },
    { id: "sites", title: "مواقع الويب", long: "مواقع الويب", sub: "تعريفي، مؤسسة، صفحة هبوط", line: "مواقع تعريفية، مواقع مؤسسات وصفحات هبوط سريعة على الهاتف." },
    { id: "shopify", title: "Shopify", long: "Shopify وصفحات المنتج", sub: "متاجر وصفحات منتجات", line: "متجرك مفتوح ومُعدّ، بصفحات منتجات تستقبل الطلبات." },
    { id: "publicite", title: "الإعلانات", long: "الإعلانات المموّلة", sub: "فيسبوك، إنستغرام، تيك توك", line: "حملات على فيسبوك وإنستغرام وتيك توك، بتصاميم تُوقف الإبهام." },
    { id: "logos", title: "الشعارات", long: "الشعارات والهوية", sub: "هوية العلامة", line: "شعار وهوية تُعرَف من بعيد، على اللافتة كما على الهاتف." },
  ],
  servicesLabel: "خدماتنا الست",
  software: {
    title: "برامج التسيير.",
    lead: "ثلاثة برامج كُتبت هنا، لتجارات هنا. مثبّتة على حواسيبك، وبياناتك تبقى عندك.",
    tabsLabel: "اختر برنامجاً",
    products: [
      {
        id: "superpos",
        name: "SuperPOS",
        what: "صندوق الدفع للمتاجر والمحلات.",
        features: [
          "واجهة بالفرنسية والعربية",
          "يعمل بدون إنترنت",
          "سريع حتى على حاسوب قديم",
          "دفتر الديون مدمج",
          "التكوين مشمول",
        ],
        proof: "شاشة حقيقية من SuperPOS، أعيد إنجازها بدقة عالية · بيانات للعرض.",
        cta: "اطلب عرضاً تجريبياً لـ SuperPOS",
        wa: "السلام عليكم Broda Dev، أريد عرضاً تجريبياً لبرنامج SuperPOS.",
        alt: "دفتر الديون في SuperPOS: قائمة الزبائن وأرصدتهم، وتفاصيل ديون ودفعات زبون",
      },
      {
        id: "gstock",
        name: "G-Stock",
        what: "المخزون وتسيير المطعم.",
        features: [
          "المشتريات وفواتير الموردين",
          "الإخراجات نحو المطبخ",
          "حالة المخزون وتنبيهات النفاد",
          "جدول عمل الموظفين",
          "الإحصائيات والحصيلة",
        ],
        proof: "يعمل في مطعم Lamssat بتلمسان. شاشة حقيقية، أرقام للعرض.",
        cta: "اطلب عرضاً تجريبياً لـ G-Stock",
        wa: "السلام عليكم Broda Dev، أريد عرضاً تجريبياً لبرنامج G-Stock.",
        alt: "لوحة تحكم G-Stock في مطعم Lamssat تلمسان: المشتريات، الإخراجات، حالة المخزون والمنتجات الواجب طلبها",
      },
      {
        id: "budget",
        name: "Budget Employé",
        what: "الموظفون، الحضور والأجور.",
        features: [
          "الحضور يوماً بيوم",
          "الأجر باليوم أو الأسبوع أو الشهر",
          "خصم التسبيقات تلقائياً",
          "المصاريف والتقارير",
        ],
        proof: "شاشة عرض لبرنامج Budget Employé.",
        cta: "اطلب عرضاً تجريبياً لـ Budget Employé",
        wa: "السلام عليكم Broda Dev، أريد عرضاً تجريبياً لبرنامج Budget Employé.",
        alt: "لوحة تحكم Budget Employé: الموظفون، الحاضرون، كتلة الأجور، أجور الشهر والتسبيقات",
      },
    ],
  },
  sites: {
    title: "مواقع الويب.",
    lead: "موقع تعريفي يجعلهم يأتون، وصفحة هبوط تجعلهم يطلبون.",
    body: "موقع تعريفي لتجارتك، موقع مؤسسة، أو صفحة هبوط لبيع منتج: سريع على الهاتف، بالفرنسية والعربية، مع زر واتساب واستمارة الطلب التي يعرفها زبائنك.",
    features: ["موقع تعريفي أو موقع مؤسسة", "صفحة هبوط لمنتج أو عرض", "سريع على الهاتف، بالفرنسية والعربية", "واتساب واستمارة الطلب مدمجان"],
    cta: "جرّب صفحة الهبوط",
    label: "أمثلة · HANOUT 13 و ZNIQA علامتان مُتخيَّلتان للعرض فقط.",
    siteAlt: "موقع تعريفي للعرض لمتجر HANOUT 13: التخفيضات، التوصيل والطلب عبر واتساب",
    landingAlt: "صفحة هبوط للعرض لتيشيرت ZNIQA على الهاتف، وزر الطلب ظاهر دائماً",
  },
  shopify: {
    title: "Shopify وصفحات المنتج.",
    lead: "صفحة منتج تستقبل الطلبات بدلاً عنك.",
    body: "صور احترافية، السعر بالدينار، المقاس واللون، واستمارة الطلب التي يعرفها زبائنك: الولاية، البلدية، التوصيل للمكتب أو للمنزل. يطلبون من هواتفهم، وتصلك الطلبية.",
    features: ["الاسم ورقم الهاتف", "58 ولاية والبلدية", "المكتب أو المنزل", "المجموع يُحسب مباشرة", "زر واحد، طلبية واحدة"],
    cta: "جرّب النموذج",
    label: "مثال · ZNIQA علامة مُتخيَّلة للعرض فقط.",
    laptopAlt: "صفحة منتج ZNIQA على الحاسوب: صور، السعر بالدينار واستمارة الطلب",
    phoneAlt: "استمارة طلب ZNIQA على الهاتف: الاسم، الهاتف، الولاية، البلدية، التوصيل والمجموع",
  },
  publicite: {
    title: "الإعلانات المموّلة.",
    lead: "حملة واحدة، ثلاث منصات، وترى ما تجلبه لك.",
    body: "نُحضّر الصور والفيديوهات، نستهدف الولايات والفئات المناسبة على فيسبوك وإنستغرام وتيك توك، ثم نتابع كل طلبية وكم كلّفت.",
    features: ["صور وفيديوهات مصمّمة لكل منصة", "استهداف حسب الولاية والسن والاهتمامات", "متابعة الطلبيات وتكلفة كل طلبية", "تقرير واضح، بالدينار"],
    cta: "أطلق حملتي",
    wa: "السلام عليكم Broda Dev، أريد إطلاق حملة إعلانية مموّلة.",
    label: "مثال · إعلانات وأرقام للعرض فقط، لعلامة مُتخيَّلة اسمها ZNIQA.",
    dashAlt: "لوحة إعلانات للعرض: المصروف، الطلبيات في اليوم، الطلبيات حسب المنصة والحملات",
    fbAlt: "منشور مموّل للعرض لعلامة ZNIQA في آخر الأخبار، مع زر الطلب",
    igAlt: "صورة مموّلة للعرض لعلامة ZNIQA، مع شريط اطلب الآن",
    ttAlt: "فيديو مموّل للعرض لعلامة ZNIQA، مع زر الطلب",
  },
  logos: {
    title: "الشعارات والهوية.",
    lead: "شعار يُعرَف من بعيد، وكل ما يرافقه.",
    body: "ننطلق من مهنتك وزبائنك، نرسم الشعار ثم نطبّقه: الألوان، بطاقات الزيارة، اللافتة، التغليف ومواقع التواصل. تستلم ملفات جاهزة للمطبعة وللهاتف.",
    brands: [
      { id: "lemma", name: "LEMMA", sector: "مقهى الحي" },
      { id: "nouara", name: "NOUARA", sector: "حقائب وجلديات" },
      { id: "hanout", name: "HANOUT 13", sector: "متجر صغير" },
      { id: "zniqa", name: "ZNIQA", sector: "ملابس الشارع" },
    ],
    card: { tagline: "مقهى الحي", hours: "مفتوح من 6سا إلى 22سا", handle: "@lemma.cafe", role: "سليم · مسيّر" },
    teeAlt: "شعار ZNIQA مطرّز على التيشيرت",
    phoneAlt: "صفحة HANOUT 13 على مواقع التواصل: الشعار كصورة الحساب ومنشورات بألوان العلامة",
    cardsAlt: "بطاقات زيارة مقهى LEMMA، الوجه والظهر",
    cta: "اطلب شعاري",
    wa: "السلام عليكم Broda Dev، أريد شعاراً لتجارتي.",
    label: "أمثلة · LEMMA و NOUARA و HANOUT 13 و ZNIQA علامات مُتخيَّلة للعرض فقط.",
  },
  why: {
    title: "لماذا Broda Dev؟",
    reasons: [
      { title: "محاور واحد.", line: "من أول رسالة إلى الإطلاق، تتعامل مع نفس الشخص. لا مقسّم هاتفي، ولا مقاول من الباطن لا تراه أبداً." },
      { title: "من هنا، لهنا.", line: "مقرّنا في تلمسان. الفرنسية والعربية، الدينار، 58 ولاية والدفع عند الاستلام: هذه نقطة انطلاقنا، لا خيار إضافي." },
      { title: "برامج تعمل فعلاً.", line: "G-Stock يسيّر مخزون مطعم Lamssat في تلمسان. برامجنا تُثبَّت على حواسيبك وتعمل حتى بدون إنترنت." },
      { title: "المحل والبيع، معاً.", line: "الصندوق الذي يحصّل والإعلان الذي يجلب الزبائن يصنعهما نفس الفريق، فيتكلّم كل شيء نفس اللغة." },
    ],
    founder: "Omar Benassid",
    role: "مؤسس Broda Dev · كيفان، تلمسان",
    write: "راسل عمر على واتساب",
  },
  process: {
    title: "كيف يتمّ العمل.",
    lead: "أربع مراحل، وتعرف دائماً أين وصل مشروعك.",
    steps: [
      { title: "نتحدث", line: "تكتب لنا على واتساب: تجارتك، وما تريد بيعه أو تسييره." },
      { title: "عرض سعر مجاني", line: "تتلقى اقتراحاً واضحاً، دون أي التزام." },
      { title: "ننجز", line: "برنامج، موقع، متجر، حملة أو شعار: نُريك التقدّم في كل مرحلة." },
      { title: "الإطلاق", line: "التثبيت أو النشر على الإنترنت. بالنسبة للبرامج، التكوين مشمول." },
    ],
  },
  contact: {
    title: "لديك مشروع؟ لنتحدث.",
    lead: "أخبرنا في سطرين بما تريد فعله. عرض السعر مجاني والرد يصلك على واتساب.",
    phoneLabel: "الهاتف",
    emailLabel: "البريد الإلكتروني",
    addressLabel: "العنوان",
    address: "كيفان، تلمسان",
    form: {
      name: "اسمك",
      namePh: "مثال: كريم",
      business: "تجارتك",
      businessPh: "مثال: متجر في منصورة",
      service: "ما تحتاجه",
      servicePh: "اختر خدمة",
      message: "رسالتك",
      messagePh: "بضع كلمات عن مشروعك",
      send: "أرسل على واتساب",
      note: "الزر يفتح واتساب ورسالتك مكتوبة مسبقاً. لا يُرسَل شيء إلى أي مكان آخر.",
      required: "اكتب على الأقل اسمك ورسالتك.",
      intro: "السلام عليكم Broda Dev،",
      labels: { name: "الاسم", business: "التجارة", service: "الخدمة" },
    },
  },
  footer: {
    services: "الخدمات",
    pages: "الصفحات",
    contact: "اتصل بنا",
    home: "الرئيسية",
    rights: "Broda Dev · تلمسان، الجزائر",
    examples: "علامة ZNIQA والنماذج الأخرى مُتخيَّلة للعرض فقط.",
  },
  whatsappLabel: "راسل Broda Dev على واتساب",
  waMessage: "السلام عليكم Broda Dev، أريد عرض سعر مجاني.",
};

export const SITE = { fr, ar };
export type SiteCopy = typeof fr;
export type Lang = keyof typeof SITE;

export const langOf = (locale: string): Lang => (locale === "ar" ? "ar" : "fr");

/**
 * Where the numbered markers sit on the phone order-form render
 * (zniqa-mobile-form), as % of the phone screen height, status bar included:
 * name, wilaya, delivery, total, order button.
 */
export const FORM_MARKERS = [29.3, 49.9, 61.8, 89.1, 96.4];
