// Site copy. French is the reference: ar is typed against it, so a missing
// key is a type error. Claims follow PRODUCT.md: nothing here is invented
// (no clients beyond Lamssat Tlemcen, no figures, no prices for our work).

const fr = {
  nav: {
    home: "Broda Dev, accueil",
    main: "Navigation principale",
    services: "Services",
    software: "Logiciels",
    work: "Réalisations",
    contact: "Contact",
    quote: "Demander un devis",
    quoteShort: "Devis gratuit",
    switchLang: "Lire en arabe",
    switchShort: "ع",
    menu: "Menu",
    close: "Fermer le menu",
    skip: "Aller au contenu",
  },
  hero: {
    // The headline chosen by the owner on 2026-09-26: the three things Broda
    // Dev does for any activity. "Du logiciel à la pub" is the sticker on
    // the stage (the till, then the ad on the phone).
    poster: ["Gérer.", "Vendre.", "Grandir."],
    title: "Gérer. Vendre. Grandir.",
    lead: "Logiciels de gestion, caisses, sites web, boutiques Shopify, publicité et logos, pour les commerces, les entreprises, les écoles et les agences de location. Depuis Tlemcen, pour toute l'Algérie.",
    stamp: "Du logiciel à la pub",
    primary: "Demander un devis gratuit",
    whatsapp: "WhatsApp",
    caption: "POS-MINI MARKET, notre logiciel de caisse · Publicité d'exemple pour ZNIQA, une marque inventée",
    posAlt: "Écran de caisse POS-MINI MARKET avec un ticket en cours et la grille des produits",
    adAlt: "Publicité vidéo sponsorisée pour la marque d'exemple ZNIQA, avec le bouton Commander",
  },
  overview: {
    title: "Sept métiers. Un seul partenaire.",
    lead: "Le logiciel qui fait tourner le magasin et tout ce qui amène les clients : on s'en occupe de A à Z, et vous parlez toujours à la même personne.",
  },
  // The seven services, in the order of the page. `id` is the section anchor.
  // A `compact` service has no section on the home: its row and the footer
  // link to its card on /services, and it takes no key under the bar.
  services: [
    { id: "logiciels", title: "Logiciels", long: "Logiciels de gestion", sub: "POS-MINI MARKET · G-Stock · Budget Employé", line: "Caisse, stock et paie, installés sur vos PC. Ils marchent même sans internet." },
    { id: "caisses", title: "Caisses POS", long: "Caisses POS", sub: "Supérettes, restaurants, cafés", line: "Un système de caisse pensé pour votre commerce : supérette, supermarché, restaurant ou café." },
    { id: "sites", title: "Sites web", long: "Sites web", sub: "Vitrine, entreprise, landing page", line: "Sites vitrines, sites d'entreprise et landing pages qui chargent vite sur téléphone." },
    { id: "shopify", title: "Shopify", long: "Shopify & pages produit", sub: "Boutiques et pages produit", line: "Votre boutique ouverte et configurée, avec des pages produit qui prennent les commandes." },
    { id: "publicite", title: "Publicité", long: "Publicité sponsorisée", sub: "Facebook, Instagram, TikTok", line: "Des campagnes sur Facebook, Instagram et TikTok, avec des visuels faits pour arrêter le pouce." },
    { id: "logos", title: "Logos", long: "Logos & identité", sub: "Identité de marque", line: "Un logo et une identité qui se reconnaissent de loin, sur l'enseigne comme sur le téléphone." },
    { id: "hebergement", title: "Hébergement", long: "Hébergement & maintenance", sub: "Domaine, hébergement, mises à jour", line: "Le nom de domaine, l'hébergement, et chaque mois les mises à jour et petites retouches : votre site reste en ligne et à jour.", compact: true },
  ],
  servicesLabel: "Nos services",
  // The free trial of POS-MINI MARKET (30 days, owner 2026-09-25), on the software and till sections.
  trial: { label: "Essai gratuit de POS-MINI MARKET", days: "30 jours", wa: "Bonjour, je veux essayer POS-MINI MARKET gratuitement." },
  // The line under the Sites web and Shopify sections, pointing to the seventh service.
  hosting: { lead: "Et après la mise en ligne :", line: "hébergement & maintenance, le domaine, l'hébergement et les petites mises à jour chaque mois.", link: "En savoir plus" },
  software: {
    title: "Logiciels de gestion.",
    lead: "Trois logiciels écrits ici, pour les commerces d'ici. Installés sur vos PC, vos données restent chez vous.",
    tabsLabel: "Choisir un logiciel",
    // The price of POS-MINI MARKET (the owner, 2026-09-26), on a sticker beside its name.
    price: { amount: "35 000", currency: "DA" },
    products: [
      {
        id: "pos-minimarket",
        name: "POS-MINI MARKET",
        what: "La caisse des supérettes et des commerces.",
        features: [
          "Interface en français et en arabe",
          "Fonctionne sans internet",
          "Rapide, même sur un vieux PC",
          "Carnet de dettes intégré",
          "Formation comprise",
        ],
        proof: "Écran de POS-MINI MARKET, recréé en HD d'après le logiciel réel · données d'exemple.",
        cta: "Demander une démo de POS-MINI MARKET",
        wa: "Bonjour Broda Dev, je voudrais une démo de POS-MINI MARKET.",
        alt: "Carnet de dettes de POS-MINI MARKET : liste des clients avec leur solde, et le détail des dettes et versements d'un client",
      },
      {
        id: "gstock",
        name: "G-Stock",
        what: "Le stock et la gestion du restaurant.",
        features: [
          "Achats et factures fournisseurs",
          "Sorties vers la cuisine",
          "État du stock et alertes de rupture",
          "Planning du personnel",
          "Statistiques et bilan",
        ],
        proof: "En service au restaurant Lamssat, à Tlemcen. Écran réel, chiffres d'exemple.",
        cta: "Demander une démo de G-Stock",
        wa: "Bonjour Broda Dev, je voudrais une démo de G-Stock.",
        alt: "Tableau de bord de G-Stock au restaurant Lamssat Tlemcen : achats, sorties, état du stock et produits à commander",
      },
      {
        id: "budget",
        name: "Budget Employé",
        what: "Le personnel, les présences et la paie.",
        features: [
          "Présences au jour le jour",
          "Paie au jour, à la semaine ou au mois",
          "Avances déduites automatiquement",
          "Dépenses et rapports",
        ],
        proof: "Écran de démonstration de Budget Employé.",
        cta: "Demander une démo de Budget\u00a0Employé",
        wa: "Bonjour Broda Dev, je voudrais une démo de Budget Employé.",
        alt: "Tableau de bord de Budget Employé : employés actifs, présents, masse salariale, paie du mois et avances",
      },
    ],
  },
  caisses: {
    title: "Caisses POS.",
    lead: "Une caisse rapide, faite pour votre commerce.",
    body: "On configure la caisse avec vos produits et vos prix, on l'installe sur votre poste après avoir vérifié votre imprimante ticket et votre lecteur de code-barres, puis on forme vos caissiers.",
    tradesLabel: "Choisir un commerce",
    trades: [
      {
        id: "superette",
        name: "Supérette",
        sub: "Supérette, supermarché",
        line: "POS-MINI MARKET est prêt à l'emploi : code-barres, plusieurs commandes en parallèle, monnaie à rendre calculée.",
        proof: "Écran de POS-MINI MARKET, recréé en HD d'après le logiciel réel. Ticket et données d'exemple : MINI MARKET est une supérette inventée.",
        alt: "Écran de paiement de POS-MINI MARKET : 3 070,00 DA à payer, 5 000 DA reçus, 1 930,00 DA de monnaie à rendre",
      },
      {
        id: "cafe",
        name: "Café",
        sub: "Café, restaurant",
        line: "Service rapide au comptoir : vos boissons et vos viennoiseries en un seul toucher. Pour un restaurant, on adapte la caisse à votre service.",
        proof: "POS-MINI MARKET configuré pour LEMMA, un café inventé. Ticket et données d'exemple.",
        alt: "Caisse POS-MINI MARKET configurée pour un café : ticket en cours de 1 010,00 DA et grille des boissons et viennoiseries",
      },
    ],
    cta: "Demander un devis pour ma caisse",
    wa: "Bonjour Broda Dev, je voudrais une caisse pour mon commerce.",
  },
  sites: {
    title: "Sites web.",
    lead: "Un site vitrine qui donne envie de venir, une landing page qui donne envie de commander.",
    body: "Site vitrine pour votre commerce, site d'entreprise, ou landing page pour vendre un produit : rapide sur téléphone, en français et en arabe, avec le bouton WhatsApp et le formulaire de commande que vos clients connaissent.",
    features: ["Site vitrine ou site d'entreprise", "Landing page pour un produit ou une offre", "Rapide sur téléphone, en français et en arabe", "WhatsApp et formulaire de commande intégrés"],
    cta: "Essayer la landing page",
    label: "Exemples · MINI MARKET et ZNIQA sont des marques inventées pour la démonstration.",
    siteAlt: "Site vitrine d'exemple de la supérette MINI MARKET : promos, livraison et commande sur WhatsApp",
    landingAlt: "Landing page d'exemple du t-shirt ZNIQA sur téléphone, avec le bouton Commander toujours visible",
  },
  shopify: {
    title: "Shopify & pages produit.",
    lead: "Une page produit qui prend les commandes pour vous.",
    body: "Photos soignées, prix en DA, taille et couleur, et le formulaire que vos clients connaissent déjà : wilaya, commune, stop desk ou domicile. Ils commandent depuis leur téléphone, vous recevez la commande.",
    features: ["Nom et téléphone", "58 wilayas et commune", "Stop desk ou domicile", "Total calculé en direct", "Un bouton, une commande"],
    cta: "Essayer la démo",
    // The two live demos the section switches between (invented brands).
    demosLabel: "Choisir la démo",
    demos: [
      {
        id: "zniqa",
        name: "ZNIQA",
        sub: "T-shirt · streetwear",
        label: "Exemple · ZNIQA est une marque inventée pour la démonstration.",
        laptopAlt: "Page produit ZNIQA sur ordinateur : galerie photo, prix en DA et formulaire de commande",
        phoneAlt: "Formulaire de commande ZNIQA sur téléphone : nom, téléphone, wilaya, commune, livraison et total",
      },
      {
        id: "nouara",
        name: "NOUARA",
        sub: "Sac à main · maroquinerie",
        label: "Exemple · NOUARA est une marque inventée pour la démonstration.",
        laptopAlt: "Page produit NOUARA sur ordinateur : galerie photo du sac, prix en DA et formulaire de commande",
        phoneAlt: "Formulaire de commande NOUARA sur téléphone : nom, téléphone, wilaya, commune, livraison et total",
      },
    ],
  },
  publicite: {
    title: "Publicité sponsorisée.",
    lead: "Une campagne, trois plateformes, et vous voyez ce qu'elle rapporte.",
    body: "On prépare les visuels et les vidéos, on cible les bonnes wilayas et les bons profils sur Facebook, Instagram et TikTok, puis on suit chaque commande et ce qu'elle a coûté.",
    features: ["Visuels et vidéos faits pour chaque plateforme", "Ciblage par wilaya, âge et centres d'intérêt", "Suivi des commandes et du coût par commande", "Un rapport clair, en dinars"],
    cta: "Lancer ma campagne",
    wa: "Bonjour Broda Dev, je voudrais lancer une campagne sponsorisée.",
    label: "Exemple · publicités et chiffres inventés pour la démonstration, pour la marque inventée ZNIQA.",
    dashAlt: "Tableau de bord publicitaire d'exemple : dépenses, commandes par jour, commandes par plateforme et campagnes",
    fbAlt: "Publication sponsorisée d'exemple pour ZNIQA dans un fil d'actualité, avec le bouton Commander",
    igAlt: "Photo sponsorisée d'exemple pour ZNIQA, avec la bande Commander maintenant",
    ttAlt: "Vidéo sponsorisée d'exemple pour ZNIQA, avec le bouton Commander",
  },
  logos: {
    title: "Logos & identité.",
    lead: "Un logo qui se reconnaît de loin, et tout ce qui va avec.",
    body: "On part de votre métier et de vos clients, on dessine le logo, puis on le décline : couleurs, cartes de visite, enseigne, emballages, réseaux sociaux. Vous recevez des fichiers prêts pour l'imprimeur et pour le téléphone.",
    brands: [
      { id: "lemma", name: "LEMMA", sector: "Café de quartier" },
      { id: "nouara", name: "NOUARA", sector: "Sacs et maroquinerie" },
      { id: "minimarket", name: "MINI MARKET", sector: "Supérette" },
      { id: "zniqa", name: "ZNIQA", sector: "Streetwear" },
    ],
    card: { tagline: "Café de quartier", hours: "Ouvert de 6 h à 22 h", handle: "@lemma.cafe", role: "Salim · gérant" },
    signAlt: "L'enseigne lumineuse de MINI MARKET au-dessus de l'entrée vitrée de la supérette",
    teeAlt: "Le logo ZNIQA brodé sur le t-shirt",
    phoneAlt: "Profil social de MINI MARKET : le logo en avatar et des publications aux couleurs de la marque",
    cardsAlt: "Cartes de visite du café LEMMA, recto et verso",
    cta: "Demander mon logo",
    wa: "Bonjour Broda Dev, je voudrais un logo pour mon commerce.",
    label: "Exemples · LEMMA, NOUARA, MINI MARKET et ZNIQA sont des marques inventées pour la démonstration.",
  },
  why: {
    title: "Pourquoi Broda Dev.",
    reasons: [
      { title: "Un seul interlocuteur.", line: "Du premier message à la mise en ligne, vous parlez à la même personne. Pas de standard, pas de sous-traitant qu'on ne voit jamais." },
      { title: "D'ici, pour ici.", line: "Basé à Tlemcen. Le français et l'arabe, les dinars, les 58 wilayas, le paiement à la livraison : c'est notre point de départ, pas une option." },
      { title: "Des logiciels qui tournent vraiment.", line: "G-Stock gère le stock du restaurant Lamssat, à Tlemcen. Nos logiciels s'installent sur vos PC et marchent même sans internet." },
      { title: "Le magasin et la vente, ensemble.", line: "La caisse qui encaisse et la pub qui fait venir les clients sont faites par la même équipe, alors tout parle la même langue." },
    ],
    founder: "Omar Benassid",
    role: "Fondateur de Broda Dev · Kiffan, Tlemcen",
    write: "Écrire à Omar sur WhatsApp",
  },
  // Real clients only, each cited with its consent. No testimonial is written for them.
  trust: {
    title: "Ils nous font confiance",
    note: "Clients réels, cités avec leur accord.",
    clients: [
      {
        name: "Lamssat Tlemcen",
        place: "Restaurant · Tlemcen",
        work: "G-Stock gère le stock du restaurant : achats, sorties, alertes et planning du personnel.",
        link: "Voir les écrans",
        href: "/logiciels#gstock",
        screen: "/images/gstock/gstock-tableau-de-bord",
        alt: "Tableau de bord de G-Stock au restaurant Lamssat Tlemcen : achats, sorties et état du stock, chiffres d'exemple",
      },
    ],
  },
  process: {
    title: "Comment ça se passe.",
    lead: "Quatre étapes, et vous savez toujours où en est votre projet.",
    steps: [
      { title: "On en parle", line: "Vous écrivez sur WhatsApp : votre commerce, ce que vous voulez vendre ou gérer." },
      { title: "Devis gratuit", line: "Vous recevez une proposition claire, sans engagement." },
      { title: "On construit", line: "Logiciel, site, boutique, campagne ou logo : on vous montre l'avancement à chaque étape." },
      { title: "Lancement", line: "Installation ou mise en ligne. Pour les logiciels, la formation est comprise." },
    ],
  },
  contact: {
    title: "Un projet ? Parlons‑en.",
    lead: "Dites-nous en deux lignes ce que vous voulez faire. Le devis est gratuit et la réponse arrive sur WhatsApp.",
    phoneLabel: "Téléphone",
    emailLabel: "E-mail",
    addressLabel: "Adresse",
    address: "Kiffan, Tlemcen",
    form: {
      name: "Votre nom",
      namePh: "Ex : Karim",
      business: "Votre commerce",
      businessPh: "Ex : supérette à Mansourah",
      service: "Ce qu'il vous faut",
      servicePh: "Choisir un service",
      message: "Votre message",
      messagePh: "Quelques mots sur votre projet",
      send: "Envoyer sur WhatsApp",
      note: "Le bouton ouvre WhatsApp avec votre message déjà écrit. Rien n'est envoyé ailleurs.",
      required: "Écrivez au moins votre nom et votre message.",
      intro: "Bonjour Broda Dev,",
      labels: { name: "Nom", business: "Commerce", service: "Service" },
    },
  },
  footer: {
    services: "Services",
    pages: "Pages",
    contact: "Contact",
    home: "Accueil",
    rights: "Broda Dev · Tlemcen, Algérie",
    examples: "Les marques ZNIQA et les autres démos sont inventées pour l'exemple.",
  },
  whatsappLabel: "Écrire à Broda Dev sur WhatsApp",
  waMessage: "Bonjour Broda Dev, je voudrais un devis gratuit.",
  // Asked before any WhatsApp link leaves the site (WhatsAppConfirm).
  leave: {
    title: "Ouvrir WhatsApp ?",
    text: "Vous allez quitter le site Broda Dev pour continuer la conversation sur WhatsApp.",
    message: "Votre message, déjà écrit",
    edit: "Vous pourrez le modifier avant de l'envoyer.",
    open: "Ouvrir WhatsApp",
    stay: "Rester sur le site",
  },
};

// Arabic written for Algerian shop and business owners (rewritten
// 2026-09-27 at the owner's request: the first version followed the French
// word for word and testers found it strange). The words people use here:
// صندوق الدفع for the till (the owner's word, 2026-09-27), الإشهار for advertising, الباركود, الصرف, التسبيق,
// التكوين, الطلبية. Same facts as the French, never more.
const ar: typeof fr = {
  nav: {
    home: "Broda Dev، الصفحة الرئيسية",
    main: "القائمة الرئيسية",
    services: "الخدمات",
    software: "البرامج",
    work: "أعمالنا",
    contact: "اتصل بنا",
    quote: "اطلب عرض سعر",
    quoteShort: "عرض سعر",
    switchLang: "Lire en français",
    switchShort: "FR",
    menu: "القائمة",
    close: "إغلاق القائمة",
    skip: "انتقل إلى المحتوى",
  },
  hero: {
    poster: ["تسيير.", "تسويق.", "توسُّع."],
    title: "تسيير. تسويق. توسُّع.",
    lead: "برامج التسيير وأجهزة صندوق الدفع، المواقع والمتاجر الإلكترونية، الإشهار والشعار: للمحلات والشركات والمدارس ووكالات الكراء، من تلمسان إلى كل الجزائر.",
    stamp: "من البرنامج إلى الإشهار",
    primary: "اطلب عرض سعر مجاني",
    whatsapp: "واتساب",
    caption: "POS-MINI MARKET، برنامج صندوق الدفع من إنجازنا · إشهار للمثال لعلامة وهمية اسمها ZNIQA",
    posAlt: "شاشة صندوق الدفع في POS-MINI MARKET: وصل بيع مفتوح وقائمة السلع",
    adAlt: "فيديو إشهاري ممول لعلامة ZNIQA الوهمية، مع زر الطلب",
  },
  overview: {
    title: "سبع خدمات. شريك واحد.",
    lead: "من البرنامج الذي تسيّر به محلك إلى الإشهار الذي يجلب لك الزبائن: نتكفّل بكل شيء، وتتعامل دائماً مع نفس الشخص.",
  },
  services: [
    { id: "logiciels", title: "البرامج", long: "برامج التسيير", sub: "POS-MINI MARKET · G-Stock · Budget Employé", line: "صندوق الدفع، المخزون ورواتب العمال، على حواسيبك. تعمل حتى بدون إنترنت." },
    { id: "caisses", title: "صندوق الدفع", long: "أجهزة صندوق الدفع", sub: "محلات، مطاعم، مقاهي", line: "صندوق دفع مضبوط على نشاطك: محل مواد غذائية، سوبر ماركت، مطعم أو مقهى." },
    { id: "sites", title: "المواقع", long: "مواقع الإنترنت", sub: "موقع تعريفي، موقع شركة، صفحة بيع", line: "موقع يعرّف بنشاطك، موقع لشركتك، أو صفحة لبيع منتج، سريعة على الهاتف." },
    { id: "shopify", title: "Shopify", long: "متاجر Shopify", sub: "متجر إلكتروني وصفحات منتجات", line: "متجرك الإلكتروني جاهز، بصفحات منتجات تستقبل الطلبيات." },
    { id: "publicite", title: "الإشهار", long: "الإشهار الممول", sub: "فيسبوك، إنستغرام، تيك توك", line: "حملات إشهارية على فيسبوك وإنستغرام وتيك توك، بصور وفيديوهات تلفت الانتباه." },
    { id: "logos", title: "الشعار", long: "الشعار والهوية", sub: "هوية علامتك", line: "شعار يعرفه الناس من بعيد، على واجهة المحل وعلى الهاتف." },
    { id: "hebergement", title: "الاستضافة", long: "الاستضافة والصيانة", sub: "اسم الموقع، الاستضافة، التحديثات", line: "نحجز اسم موقعك ونستضيفه، ونقوم كل شهر بالتحديثات والتعديلات الصغيرة: يبقى موقعك يعمل ومحدّثاً.", compact: true },
  ],
  servicesLabel: "خدماتنا",
  trial: { label: "جرّب POS-MINI MARKET مجاناً", days: "30 يوماً", wa: "السلام عليكم، أريد تجربة POS-MINI MARKET مجاناً." },
  hosting: { lead: "وبعد إطلاق الموقع:", line: "نتكفّل باسم الموقع والاستضافة والتحديثات الصغيرة كل شهر.", link: "اعرف المزيد" },
  software: {
    title: "برامج التسيير.",
    lead: "ثلاثة برامج من إنجازنا، على مقاس المحلات عندنا. تُثبَّت على حواسيبك، ومعلوماتك تبقى عندك.",
    tabsLabel: "اختر برنامجاً",
    price: { amount: "35 000", currency: "دج" },
    products: [
      {
        id: "pos-minimarket",
        name: "POS-MINI MARKET",
        what: "برنامج صندوق الدفع للمحلات والسوبر ماركت.",
        features: [
          "بالعربية والفرنسية",
          "يعمل بدون إنترنت",
          "سريع حتى على حاسوب قديم",
          "دفتر الديون (الكريدي) مدمج",
          "التكوين مشمول",
        ],
        proof: "شاشة POS-MINI MARKET أعدنا رسمها بجودة عالية من البرنامج الحقيقي · الأرقام للمثال فقط.",
        cta: "اطلب عرضاً تجريبياً لـ POS-MINI MARKET",
        wa: "السلام عليكم Broda Dev، أريد عرضاً تجريبياً لبرنامج POS-MINI MARKET.",
        alt: "دفتر الديون في POS-MINI MARKET: قائمة الزبائن وما على كل واحد، وتفاصيل ديون زبون ودفعاته",
      },
      {
        id: "gstock",
        name: "G-Stock",
        what: "تسيير مخزون المطعم.",
        features: [
          "المشتريات وفواتير المورّدين",
          "ما يخرج من المخزن إلى المطبخ",
          "كمية كل سلعة، وتنبيه قبل أن تنفد",
          "جدول أوقات العمال",
          "الإحصائيات وحصيلة الشهر",
        ],
        proof: "يستعمله مطعم Lamssat في تلمسان. الشاشة حقيقية، والأرقام للمثال.",
        cta: "اطلب عرضاً تجريبياً لـ G-Stock",
        wa: "السلام عليكم Broda Dev، أريد عرضاً تجريبياً لبرنامج G-Stock.",
        alt: "لوحة G-Stock في مطعم Lamssat تلمسان: المشتريات، ما خرج إلى المطبخ، المخزون والسلع التي يجب طلبها",
      },
      {
        id: "budget",
        name: "Budget Employé",
        what: "العمال، الحضور والرواتب.",
        features: [
          "الحضور يوماً بيوم",
          "الراتب باليوم أو الأسبوع أو الشهر",
          "خصم التسبيقات وحده",
          "المصاريف والتقارير",
        ],
        proof: "شاشة للمثال من Budget Employé.",
        cta: "اطلب عرضاً تجريبياً لـ Budget Employé",
        wa: "السلام عليكم Broda Dev، أريد عرضاً تجريبياً لبرنامج Budget Employé.",
        alt: "لوحة Budget Employé: عدد العمال، الحاضرون اليوم، مجموع الرواتب، رواتب الشهر والتسبيقات",
      },
    ],
  },
  caisses: {
    title: "أجهزة صندوق الدفع.",
    lead: "صندوق دفع سريع، مضبوط على نشاطك.",
    body: "ندخل سلعك وأسعارك في صندوق الدفع، ونركّبه على جهازك بعد تجربة طابعة الوصولات وقارئ الباركود، ثم نكوّن من سيعمل عليه.",
    tradesLabel: "اختر نوع نشاطك",
    trades: [
      {
        id: "superette",
        name: "مواد غذائية",
        sub: "محل مواد غذائية، سوبر ماركت",
        line: "POS-MINI MARKET جاهز للعمل: قراءة الباركود، عدة زبائن في نفس الوقت، والصرف يُحسب وحده.",
        proof: "شاشة POS-MINI MARKET أعدنا رسمها بجودة عالية من البرنامج الحقيقي. الوصل والأرقام للمثال، و MINI MARKET محل وهمي.",
        alt: "شاشة الدفع في POS-MINI MARKET: المبلغ 3 070,00 دج، الزبون دفع 5 000 دج، والصرف 1 930,00 دج",
      },
      {
        id: "cafe",
        name: "مقهى",
        sub: "مقهى، مطعم",
        line: "خدمة سريعة: مشروباتك وحلوياتك بلمسة واحدة. وللمطاعم، نضبط صندوق الدفع على طريقة عملك.",
        proof: "POS-MINI MARKET مضبوط لـ LEMMA، مقهى وهمي. الوصل والأرقام للمثال.",
        alt: "صندوق الدفع POS-MINI MARKET مضبوط لمقهى: وصل مفتوح بـ 1 010,00 دج وقائمة المشروبات والحلويات",
      },
    ],
    cta: "اطلب عرض سعر لصندوق الدفع",
    wa: "السلام عليكم Broda Dev، أريد صندوق دفع لمحلي.",
  },
  sites: {
    title: "مواقع الإنترنت.",
    lead: "موقع يعرّفهم بك، وصفحة بيع تجعلهم يطلبون.",
    body: "موقع يعرّف بنشاطك، موقع لشركتك، أو صفحة لبيع منتج واحد: سريع على الهاتف، بالعربية والفرنسية، مع زر واتساب واستمارة الطلب التي يعرفها زبائنك.",
    features: ["موقع تعريفي أو موقع شركة", "صفحة بيع لمنتج أو عرض", "سريع على الهاتف، بالعربية والفرنسية", "زر واتساب واستمارة الطلب"],
    cta: "جرّب صفحة البيع",
    label: "أمثلة · MINI MARKET و ZNIQA علامتان وهميتان للمثال فقط.",
    siteAlt: "موقع تعريفي للمثال لمحل MINI MARKET: التخفيضات، التوصيل والطلب عبر واتساب",
    landingAlt: "صفحة بيع للمثال لتيشيرت ZNIQA على الهاتف، وزر الطلب ظاهر دائماً",
  },
  shopify: {
    title: "متجرك على Shopify.",
    lead: "صفحة منتج تستقبل الطلبيات مكانك.",
    body: "صور احترافية، السعر بالدينار، المقاس واللون، واستمارة الطلب التي يعرفها زبائنك: الولاية، البلدية، والتوصيل إلى المكتب أو إلى المنزل. يطلبون من هواتفهم، وتصلك الطلبية.",
    features: ["الاسم ورقم الهاتف", "الـ58 ولاية والبلدية", "إلى المكتب أو إلى المنزل", "المجموع يُحسب وحده", "زر واحد وتصلك الطلبية"],
    cta: "جرّب المثال",
    demosLabel: "اختر المثال",
    demos: [
      {
        id: "zniqa",
        name: "ZNIQA",
        sub: "تيشيرت · ملابس شبابية",
        label: "مثال · ZNIQA علامة وهمية للمثال فقط.",
        laptopAlt: "صفحة منتج ZNIQA على الحاسوب: الصور، السعر بالدينار واستمارة الطلب",
        phoneAlt: "استمارة طلب ZNIQA على الهاتف: الاسم، الهاتف، الولاية، البلدية، التوصيل والمجموع",
      },
      {
        id: "nouara",
        name: "NOUARA",
        sub: "حقيبة يد · جلد",
        label: "مثال · NOUARA علامة وهمية للمثال فقط.",
        laptopAlt: "صفحة منتج NOUARA على الحاسوب: صور الحقيبة، السعر بالدينار واستمارة الطلب",
        phoneAlt: "استمارة طلب NOUARA على الهاتف: الاسم، الهاتف، الولاية، البلدية، التوصيل والمجموع",
      },
    ],
  },
  publicite: {
    title: "الإشهار الممول.",
    lead: "حملة واحدة على ثلاث منصات، وترى بالأرقام ما تجلبه لك.",
    body: "نحضّر الصور والفيديوهات، ونختار الولايات والزبائن المناسبين على فيسبوك وإنستغرام وتيك توك، ثم نتابع كل طلبية وكم كلّفت.",
    features: ["صور وفيديوهات لكل منصة", "استهداف حسب الولاية والعمر والاهتمامات", "عدد الطلبيات وتكلفة كل طلبية", "تقرير واضح بالدينار"],
    cta: "أطلق حملتي",
    wa: "السلام عليكم Broda Dev، أريد إطلاق حملة إشهارية ممولة.",
    label: "مثال · الإشهارات والأرقام للمثال فقط، لعلامة وهمية اسمها ZNIQA.",
    dashAlt: "لوحة إشهار للمثال: المصروف، الطلبيات في اليوم، الطلبيات حسب المنصة والحملات",
    fbAlt: "منشور ممول للمثال لعلامة ZNIQA على فيسبوك، مع زر الطلب",
    igAlt: "صورة ممولة للمثال لعلامة ZNIQA على إنستغرام، مع شريط «اطلب الآن»",
    ttAlt: "فيديو ممول للمثال لعلامة ZNIQA على تيك توك، مع زر الطلب",
  },
  logos: {
    title: "الشعار والهوية.",
    lead: "شعار يعرفه الناس من بعيد، وكل ما يلزمه.",
    body: "نبدأ من نشاطك وزبائنك، نرسم الشعار ثم نطبّقه على كل شيء: الألوان، بطاقات الزيارة، واجهة المحل، التغليف وصفحات التواصل. تستلم ملفات جاهزة للطباعة وللهاتف.",
    brands: [
      { id: "lemma", name: "LEMMA", sector: "مقهى الحي" },
      { id: "nouara", name: "NOUARA", sector: "حقائب جلدية" },
      { id: "minimarket", name: "MINI MARKET", sector: "سوبر ماركت" },
      { id: "zniqa", name: "ZNIQA", sector: "ملابس شبابية" },
    ],
    card: { tagline: "مقهى الحي", hours: "مفتوح من 6سا إلى 22سا", handle: "@lemma.cafe", role: "سليم · المسيّر" },
    signAlt: "لافتة MINI MARKET المضيئة فوق مدخل المحل",
    teeAlt: "شعار ZNIQA مطرّز على تيشيرت",
    phoneAlt: "صفحة MINI MARKET على مواقع التواصل: الشعار كصورة للحساب، ومنشورات بألوان العلامة",
    cardsAlt: "بطاقات زيارة مقهى LEMMA، من الأمام ومن الخلف",
    cta: "اطلب شعاري",
    wa: "السلام عليكم Broda Dev، أريد شعاراً لمحلي.",
    label: "أمثلة · LEMMA و NOUARA و MINI MARKET و ZNIQA علامات وهمية للمثال فقط.",
  },
  why: {
    title: "لماذا Broda Dev؟",
    reasons: [
      { title: "شخص واحد يتابعك.", line: "من أول رسالة إلى يوم الإطلاق، تتعامل مع نفس الشخص. لا نحوّلك من واحد لآخر، ولا نعطي عملك لغيرنا." },
      { title: "من تلمسان، لكل الجزائر.", line: "العربية والفرنسية، الدينار، الـ58 ولاية والدفع عند الاستلام: هذا أساس عملنا، وليس خدمة إضافية." },
      { title: "برامج مجرّبة في الميدان.", line: "G-Stock يسيّر مخزون مطعم Lamssat في تلمسان. برامجنا تُثبَّت على حواسيبك وتعمل حتى بدون إنترنت." },
      { title: "التسيير والبيع، فريق واحد.", line: "صندوق الدفع الذي يحسب مبيعاتك والإشهار الذي يجلب لك الزبائن يصنعهما نفس الفريق، فيعمل كل شيء بتناسق." },
    ],
    founder: "Omar Benassid",
    role: "مؤسس Broda Dev · كيفان، تلمسان",
    write: "راسل عمر على واتساب",
  },
  trust: {
    title: "يثقون بنا",
    note: "زبائن حقيقيون، ذكرنا أسماءهم بموافقتهم.",
    clients: [
      {
        name: "Lamssat Tlemcen",
        place: "مطعم · تلمسان",
        work: "G-Stock يسيّر مخزون المطعم: المشتريات، ما يخرج إلى المطبخ، التنبيهات وجدول العمال.",
        link: "شاهد الشاشات",
        href: "/logiciels#gstock",
        screen: "/images/gstock/gstock-tableau-de-bord",
        alt: "لوحة G-Stock في مطعم Lamssat Tlemcen: المشتريات، ما خرج إلى المطبخ والمخزون، والأرقام للمثال",
      },
    ],
  },
  process: {
    title: "كيف نعمل.",
    lead: "أربع مراحل، وتعرف دائماً أين وصل مشروعك.",
    steps: [
      { title: "نتحدث", line: "تكتب لنا على واتساب: ما هو نشاطك، وماذا تريد أن تبيع أو تسيّر." },
      { title: "عرض سعر مجاني", line: "يصلك اقتراح واضح، بدون أي التزام." },
      { title: "ننجز", line: "برنامج، موقع، متجر، حملة أو شعار: نريك التقدّم في كل مرحلة." },
      { title: "الإطلاق", line: "التركيب أو النشر على الإنترنت. وللبرامج، التكوين مشمول." },
    ],
  },
  contact: {
    title: "لديك مشروع؟ لنتحدث.",
    lead: "اكتب لنا في سطرين ما تريد. عرض السعر مجاني، والرد يصلك على واتساب.",
    phoneLabel: "الهاتف",
    emailLabel: "البريد الإلكتروني",
    addressLabel: "العنوان",
    address: "كيفان، تلمسان",
    form: {
      name: "اسمك",
      namePh: "مثال: كريم",
      business: "نشاطك",
      businessPh: "مثال: محل مواد غذائية في منصورة",
      service: "ماذا تحتاج؟",
      servicePh: "اختر خدمة",
      message: "رسالتك",
      messagePh: "كلمات قليلة عن مشروعك",
      send: "أرسل عبر واتساب",
      note: "الزر يفتح واتساب ورسالتك مكتوبة. لا نرسل معلوماتك إلى أي مكان آخر.",
      required: "اكتب اسمك ورسالتك على الأقل.",
      intro: "السلام عليكم Broda Dev،",
      labels: { name: "الاسم", business: "النشاط", service: "الخدمة" },
    },
  },
  footer: {
    services: "الخدمات",
    pages: "الصفحات",
    contact: "اتصل بنا",
    home: "الرئيسية",
    rights: "Broda Dev · تلمسان، الجزائر",
    examples: "ZNIQA والعلامات الأخرى في الأمثلة وهمية، للمثال فقط.",
  },
  whatsappLabel: "راسل Broda Dev على واتساب",
  waMessage: "السلام عليكم Broda Dev، أريد عرض سعر مجاني.",
  leave: {
    title: "فتح واتساب؟",
    text: "ستخرج من موقع Broda Dev لتكمل الحديث على واتساب.",
    message: "رسالتك جاهزة",
    edit: "يمكنك تعديلها قبل الإرسال.",
    open: "افتح واتساب",
    stay: "ابقَ في الموقع",
  },
};

export const SITE = { fr, ar };
export type SiteCopy = typeof fr;
export type Lang = keyof typeof SITE;

export const langOf = (locale: string): Lang => (locale === "ar" ? "ar" : "fr");

/**
 * Where the numbered markers sit on the phone order-form renders
 * (`<demo>-mobile-form`), as % of the phone screen height, status bar
 * included: name, wilaya, delivery, total, order button. Both demos share
 * CodOrderForm, and render.mjs scrolls each so its form lines up with the
 * other: NOUARA's steps sit 0.1 % higher (measured 2026-09-25).
 */
export const FORM_MARKERS: Record<"zniqa" | "nouara", number[]> = {
  zniqa: [29.3, 49.9, 61.8, 89.1, 96.4],
  nouara: [29.2, 49.8, 61.7, 89.0, 96.3],
};
